### ISSUE TITLE
Type Eror

### ISSUE THREAD

**Issue by YussGG** [nhanaz-pm-pl/KeepInventory#12]
in_array(): Argument #2 ($haystack) must be of type array, bool given

line 34

**Comment by NhanAZ** [comment]
Please delete your config.
Configuration has been set incorrectly.
The `worlds` field should be:
`worlds: []` or `worlds: ["pvp"]` or `worlds: ["pvp", "skyblock"]` 
This is the wrong way
`worlds:` or `worlds: pvp` or `worlds: pvp skyblock`
