### ISSUE TITLE
crash after die

### ISSUE THREAD

**Issue by UnknownNull** [nhanaz-pm-pl/KeepInventory#13]
2023-07-04 [06:51:26.446] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: Cheetah
2023-07-04 [06:51:26.447] [Server thread/CRITICAL]: TypeError: "in_array(): Argument #2 ($haystack) must be of type array, bool given" (EXCEPTION) in "plugins/KeepInventory.phar/src/NhanAZ/KeepInventory/Main" at line 34
--- Stack trace ---
  #0 plugins/KeepInventory.phar/src/NhanAZ/KeepInventory/Main(34): in_array(string[9] survival1, false)
  #1 pmsrc/src/event/RegisteredListener(61): NhanAZ\KeepInventory\Main->onPlayerDeath(object pocketmine\event\player\PlayerDeathEvent#29507)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerDeathEvent#29507)
  #3 pmsrc/src/player/Player(2335): pocketmine\event\Event->call()
  #4 pmsrc/src/entity/Entity(550): pocketmine\player\Player->onDeath()
  #5 pmsrc/src/entity/Entity(588): pocketmine\entity\Entity->kill()
  #6 pmsrc/src/entity/Living(190): pocketmine\entity\Entity->setHealth(float -980)
  #7 pmsrc/src/entity/Entity(535): pocketmine\entity\Living->setHealth(float -980)
  #8 pmsrc/src/entity/Living(539): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageEvent#101728)
  #9 pmsrc/src/player/Player(2451): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageEvent#101728)
  #10 pmsrc/src/command/defaults/KillCommand(56): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageEvent#101728)
  #11 pmsrc/src/command/SimpleCommandMap(212): pocketmine\command\defaults\KillCommand->execute(object pocketmine\player\Player#177991, string[4] kill, array[0])
  #12 pmsrc/src/Server(1427): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#177991, string[4] kill)
  #13 pmsrc/src/player/Player(1508): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#177991, string[4] kill)
  #14 pmsrc/src/network/mcpe/handler/InGamePacketHandler(852): pocketmine\player\Player->chat(string[5] /kill)
  #15 pmsrc/vendor/arabskills/bedrock-protocol/src/CommandRequestPacket(59): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#30081)
  #16 pmsrc/src/network/mcpe/NetworkSession(534): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#77117)
  #17 pmsrc/src/network/mcpe/NetworkSession(477): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#30081, string[26] M./kill.9IK.a~H_......L...)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[29] ..e.....a...^.X....z;k.$.F...)
  #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 4, string[30] ...e.....a...^.X....z;k.$.F...)
  #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#44538)
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #22 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #24 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688453486.4569)
  #25 pmsrc/src/Server(1075): pocketmine\Server->tickProcessor()
  #26 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[58] C:\Users\Administrator\Documents\MV - RL\2.survival - pm5\, string[66] C:\Users\Administrator\Documents\MV - RL\2.survival - pm5\plugins\)
  #27 pmsrc/src/PocketMine(357): pocketmine\server()

**Comment by NhanAZ** [comment]
You have set up the wrong configuration.
`worlds: ["survival1"]` not `worlds: "survival1"` or `worlds: survival1`
Check out this issue to know more: https://github.com/nhanaz-pm-pl/KeepInventory/issues/12

**Comment by UnknownNull** [comment]
![Screenshot_20230704-131255_Microsoft Remote Desktop](https://github.com/nhanaz-pm-pl/KeepInventory/assets/91208232/fb3d2263-78eb-4b02-af93-8ad00d3662f2)

**Comment by NhanAZ** [comment]
You are using the old configuration.
Please perform the following steps:
1. Delete old configuration (config.yml) [PocketMine-MP/plugin_data/KeepInventory/config.yml]
2. Restart the server to load the new configuration
3. Shut down the server and reconfigure.

**Comment by UnknownNull** [comment]
not fixed

**Comment by NhanAZ** [comment]
I can assure you this error is not caused by plugin, you have misconfigured, please show your current config.

**Comment by UnknownNull** [comment]
```
---
# blacklist: Keep inventory is false in the listed worlds.
# whitelist: Keep inventory is true in the listed worlds.
mode: whitelist
Worlds: ["survival2", "lobby", "mine", "market"]
...
```

**Comment by NhanAZ** [comment]
`worlds` not `Worlds`
