### ISSUE TITLE
[Suggestions] Whitelist/Blacklist option

### ISSUE THREAD

**Issue by PushkarOP** [nhanaz-pm-pl/KeepInventory#6]
Add blacklist World options

**Comment by NhanAZ** [comment]
> Add blacklist World options

Thanks for the suggestion

**Comment by NhanAZ** [comment]
@PushkarOP Issues solved. Thanks for the suggestion.

> This issue is solved by commit https://github.com/nhanaz-pm-pl/KeepInventory/commit/9a631c793b7983a9bfff989559a8b11c5324fd1d

**Comment by NhanAZ** [comment]
I will notify you and close this issue when v2.0.0 is approved

**Comment by NhanAZ** [comment]
v2.0.0 has been released

https://poggit.pmmp.io/p/KeepInventory/2.0.0
