### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ZippingBoat9588** [nhanaz-pm-pl/KeepInventory#7]
Can you add keep XP?

**Comment by DavidGlitch04** [comment]
As the name suggests, it only holds inventory.

**Comment by NhanAZ** [comment]
I'll do it in another plugin as soon as I can.

**Comment by NhanAZ** [comment]
Thanks for the idea. Download `KeepExp` at:
- https://github.com/nhanaz-pm-pl/KeepExp
- https://poggit.pmmp.io/ci/nhanaz-pm-pl/KeepExp/

Wish you a good day!
