### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by UnknownNull** [nhanaz-pm-pl/KeepInventory#9]
after die remove armor...

KeepInventory: true
Mode: blacklist
Worlds: [test]

**Comment by NhanAZ** [comment]
Fixed by https://github.com/nhanaz-pm-pl/KeepInventory/commit/ec115877db5dae7528532f168aa925d000cd6d38

**Comment by NhanAZ** [comment]
Download the latest version at: https://poggit.pmmp.io/p/KeepInventory/2.1.4

**Comment by UnknownNull** [comment]
new bug..
not drop items after die in new update

**Comment by NhanAZ** [comment]
What are you expecting?

**Comment by UnknownNull** [comment]
> What are you expecting?

True: keep inventory 
False: drop items and armor

**Comment by UnknownNull** [comment]
But im set this, but not drop item in test world

KeepInventory: true
Mode: blacklist
Worlds: [test]

**Comment by UnknownNull** [comment]
And not keep items

**Comment by NhanAZ** [comment]
You need to read the description carefully...
```yaml
# all : All worlds will be affected by KeepInventory Mode
# whitelist : All worlds listed below will be affected by KeepInventory Mode
# blacklist : All worlds not listed below will be affected by KeepInventory Mode
```

**Comment by UnknownNull** [comment]
> You need to read the description carefully...
> 
> ```yaml
> # all : All worlds will be affected by KeepInventory Mode
> # whitelist : All worlds listed below will be affected by KeepInventory Mode
> # blacklist : All worlds not listed below will be affected by KeepInventory Mode
> ```

The problem is that the items should be dropped, but they are completely deleted

**Comment by NhanAZ** [comment]
That's not the problem of this plugin, please check your other plugins.

**Comment by UnknownNull** [comment]
yes this work, ty
